apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-dash-ingress
  namespace: kubernetes-dashboard
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kube-dash.icsdemo.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 8443
